# Generated by Django 6.0.5 on 2026-05-22 14:28
# Generated by Django 6.0.5 on 2026-05-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milkdata',
            name='gas',
        ),
        migrations.AddField(
            model_name='milkdata',
            name='colour',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='fat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='odor',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='milkdata',
            name='taste',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='milkdata',
<<<<<<< HEAD
=======
            name='ph',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='milkdata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='milkdata',
>>>>>>> f8591ab (Add backend sensor model, migration and demo files)
            name='turbidity',
            field=models.FloatField(default=0.0),
        ),
    ]
