# Generated by Django 6.0.5 on 2026-05-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GOOD', 'Good'), ('BAD', 'Bad')], max_length=10)),
                ('adulteration_type', models.CharField(blank=True, max_length=50, null=True)),
                ('percentage', models.FloatField(default=0.0)),
                ('reasons', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('milk_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='sensors.milkdata')),
            ],
        ),
    ]
