# Generated by Django 6.0.5 on 2026-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='status',
            field=models.CharField(choices=[('PURE', 'Pure'), ('ADULTERATED', 'Adulterated')], max_length=20),
        ),
    ]
